theme: "hugo-PaperMod"
baseURL: https://a-byte-size-blog.netlify.app/
languageCode: en-us
title: A Byte Size Blog


params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Ankit Deshmukh
