theme: "hugo-PaperMod"
baseURL: https://a-byte-size-blog.netlify.app/
languageCode: en-us
title: A Byte Size Blog!

paginate: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true


languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10


params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Ankit Deshmukh - https://www.ankitdeshmukh.com"
    author: Dr. Ankit Deshmukh
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: anixn
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Dr. Ankit Deshmukh"
        Content: >
            Welcome to my blog, I will post blogs of my learnings.
            - **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.
            - Do give a 🌟 on Github !
            - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).
    socialIcons:
        - name: github
          url: "https://github.com/anixn"
        - name: linkedin
          url: "https://www.linkedin.com/in/anixn/"
        - name: website
          url: "https://www.ankitdeshmukh.com/"

    analytics:
        google:
            SiteVerificationTag: "G-R5FJKDQD1M"
