theme: "hugo-PaperMod"
baseURL: https://bytesize-blog.netlify.app/
languageCode: en-us
title: Bytesize Blog

paginate: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

googleAnalytics: 'G-R5FJKDQD1M'

minify:
    disableXML: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Blogs
                  url: /post/
                  weight: 10
                - name: Research
                  url: /Research/
                  weight: 11
                - name: Slides
                  url: /Slides/
                  weight: 20
                - name: Storytelling
                  url: /Storytelling/
                  weight: 25
                - name: Archive
                  url: archives
                  weight: 30
                - name: Tags
                  url: tags/
                  weight: 40
                - name: "  🔍  "
                  url: search/
                  weight: 50

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Ankit Deshmukh - https://www.ankitdeshmukh.com"
    author: Dr. Ankit Deshmukh

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShareButtons: ["linkedin", "twitter"] # To customize which share buttons to be enabled on page
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    TocOpen: false
    comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: true
        title: "Dr. Ankit Deshmukh"
        subtitle: ⟨●⟩ <br /><br /> `Academician | Water Resource | Hydrologic Modeling | GIS Enthusiast | Data Analysis | Freelance` <br /> <br />
        imageUrl: "Avatar.jpg"
        imageTitle: my image
        imageWidth: 160
        imageHeight: 160
        buttons:
            - name: About me
              url: /About
            - name: Blogs
              url: /post
            - name: Research
              url: /Research


    homeInfoParams:
        Title: "Dr. Ankit Deshmukh"
        Content: >
            Welcome to my blog, I will be posting the blogs of my learnings in the field of Data Visulization, R-Programming, Machine Learning, and Hydrology. Use [Categories](https://bytesize-blog.netlify.app/categories/) tab to filter out post for aformensioned categories. Do give a 🌟 on [Github](https://github.com/anixn)! For colebration and webinar reach out to me on [Twitter](https://twitter.com/anix7n).

    socialIcons:
        - name: github
          url: "https://github.com/anixn"
        - name: linkedin
          url: "https://www.linkedin.com/in/anixn/"
        - name: twitter
          url: "https://twitter.com/anix7n"
        - name: website
          url: "https://www.ankitdeshmukh.com/"

    analytics:
        google:
            SiteVerificationTag: "G-R5FJKDQD1M"

    hideFooter: true

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "favicon.ico"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary


markup:
  goldmark:
    renderer:
      unsafe: true
